site :opscode

cookbook 'apt'
cookbook 'database'
cookbook 'java'
cookbook 'git'
cookbook 'hostname'
cookbook 'mongodb'
cookbook 'monit'
cookbook 'neo4j-server', :git => 'http://github.com/michaelklishin/neo4j-server-chef-cookbook'
cookbook 'nginx'
cookbook 'nodejs'
cookbook 'ntp'
cookbook 'openssh'
cookbook 'postgresql'
cookbook 'sudo'
cookbook 'htop'